version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "6969:6969"
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=http://localhost:6969/api/auth/google/callback
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
      - FACEBOOK_REDIRECT_URI=http://localhost:6969/api/auth/facebook/callback
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=holland_lops
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: